#!/bin/bash

# 3rd Year 1st Semester OS Lab - Information Technology
# Section: A2
# Team Number: 02
#    Team Member Names                   Roll Numbers
# 1. Abishkar Chatterjee (Team Leader) - 002311001080
# 2. Atrij Roy                         - 002311001086
# 3. Soyeb Hoque                       - 002311001065
#
# Assignment: 1A (6 Marks) [CO1]
# Description: Familiarity with User and System level OS Commands
# Run the commands and validate the output.

# How to run this file:
# All the commands are commentified in this file, if you want to run any particular command, remove the hash and then move into this directory in the terminal and write:
# chmod +x A2_02_1A.sh
# And then, run the script with:
# ./A2_02_1A.sh
# If you want to see the outputs, you have to save them in a file by doing:
# ./A2_02_1A.sh > output.txt
# Then all the outputs generated by commands will be saved in that txt file.




# Q1. Description: who displays information about all users currently logged into the system.
# Command:
# who
# Output:
# username  ttyX   YYYY-MM-DD HH:MM (:0)
# (Shows one line per user currently logged in.)


# Q2. Description: whoami displays the current logged-in user's username.
# Command:
# whoami
# Output:
# username
# (This is the currently logged-in user executing the script.)


# Q3. Description: pwd prints the current working directory.
# Command:
# pwd
# Output:
# /home/username/directory
# (Displays the full path of the current directory.)


# Q4. Description: date displays the system’s current date and time.
# Command:
# date
# Output:
# Wed Jul 23 12:34:56 IST 2025
# (Format may vary depending on locale settings.)


# Q5. Description: ls lists files and directories in the current directory.
# Command:
# ls
# Output:
# file1.txt  dir1  script.sh
# (Lists all visible files and directories.)


# Q6. Description: mkdir creates a new directory with the given name.
# Command:
# mkdir new_directory
# Output:
# None
# (Use "ls" to confirm creation. If the directory exists, it shows: mkdir: cannot create directory 'new_directory': File exists)


# Q7. Description: clear clears the terminal screen.
# Command:
# clear
# Output:
# (Terminal is cleared; previous content disappears.)


# Q8. Description: cd changes the current working directory to the specified directory.
# Command:
# cd new_directory
# Output:
# None
# (No output if successful. If directory doesn't exist: bash: cd: new_directory: No such file or directory)


# Q9. Description: df displays disk space usage of mounted file systems.
# Command:
# df
# Output:
# Filesystem     1K-blocks    Used Available Use% Mounted on
# /dev/sda1      100000000 5000000 95000000   5% /
# (Exact values will vary based on the system.)


# Q10. Description: rmdir deletes the specified empty directory.
# Command:
# rmdir new_directory
# Output:
# None
# (If directory is not empty: rmdir: failed to remove 'new_directory': Directory not empty)


# Q11. Description: cat displays the content of a specified file.
# Command:
# cat file.txt
# Output:
# (Prints contents of the file to the terminal. If file doesn't exist: cat: file.txt: No such file or directory)


# Q12. Description: cp copies files from SOURCE to DEST, or multiple SOURCE(s) to DIRECTORY.
# MUST have a source file in the specified source directory for the command to work. (In this case source_file must be a file in the same directory as the .sh file.)
# Command:
# cp source_file destination_file
# Output: 
# None
# (The source file name specified is copied into a new name specified as the destination file, to see that use "ls".)
# If the file doesn't exist, it outputs an error like:
# cp: cannot stat 'source_file': No such file or directory

 
# Q13. Description: mv renames SOURCE filename to DEST filename, or move SOURCE file(s) to specified DIRECTORY.
# MUST have a source file with the specified name for the command to work. (In this case old_file must be a file in the same directory as the .sh file.)
# Command:
# mv old_file new_file
# Output: 
# None
# (The old file name specified is renamed into the name specified as "new_file", to see that use "ls".)
# If the file doesn't exist, it outputs an error like:
# mv: cannot stat 'old_file': No such file or directory


# Q14. Description: rm removes each specified file as long as it exists. By default, it does not remove directories. To remove directories, use the -r option along with rm. (rm -r <directory>)
# MUST have a source file with the specified name for the command to work. (In this case source_file must be a file in the same directory as the .sh file.)
# Command:
# rm source_file
# Output:
# None
# (The source file is deleted if permissions permit. To see the result, use "ls")
# If the file doesn't exist, it outputs an error like:
# mv: cannot remove 'source_file': No such file or directory


# Q15. Description: stat displays file or file system status. MUST have the specified file in the directory specified. (In this case new_file must be a file in the same directory as the .sh file)
# Command:
# stat new_file
# Output:
#    File: 'new_file'
#    Size: 27              Blocks: 8          IO Block: 4096   regular file
#  Device: fd02h/64770d    Inode: 6711095862  Links: 1
#  Access: (0644/-rw-r--r--)  Uid: ( 3283/  be2380)   Gid: ( 2926/  ugyr23)
#  Context: unconfined_u:object_r:user_home_t:s0
#  Access: 2025-07-23 14:08:27.934589742 +0530
#  Modify: 2025-07-23 14:08:27.934589742 +0530
#  Change: 2025-07-23 14:08:37.593589964 +0530
#
# If the file doesnt exist, the output is an error:
# stat: cannot stat 'new_file': No such file or directory


# Q16. Description: ln creates a link to TARGET with the name LINK_NAME. That is, it doesn't duplicate the file, instead, it creates a reference (link) to the same file on disk. 
# Changing the contents through the link changes the original too (for hard links).   
# By default, each destination (name of new link) should not already exist.  When creating hard links, each TARGET must exist. (In this case, new_file must be a file in the same directory as the .sh file)
# Symbolic links can hold arbitrary text; if later resolved, a relative link is interpreted in relation to its parent directory.
# Command:
# ln new_file link1
# Output:
# None
# (It creates a link with the specified name, in this case "link1", in the same directory. To see, use "ls")
# If the file doesn't exist, the output is an error:
# ln: failed to access 'new_file': No such file or directory


# Q17. Description: tty prints the file name of the terminal connected to standard input. 
# It can give different results on different computers or sessions, because it shows the terminal device you’re currently using.
# Command:
# tty
# Output: 
# /dev/pts/16


# Q18. Description: uname prints certain system information.
# Command:
# uname
# Output:
# Linux


# Q19. Description: umask stands for "user file creation mask".
# It defines which default permissions to remove when a new file or directory is created.
# umask specifies user file creation mask, implying which of the 3 permissions are to be denied to the owner, group and others.
# Command:
# umask
# Output:
# 0022


# Q20. Description: find searches the directory tree rooted at each given starting-point  by  evaluating  the  given expression from left to right, according to the rules of precedence
# (see section OPERATORS), until the outcome is known (the left hand side is false for and operations, true for or), at which point find moves on to the next file name. 
# If no starting-point is specified, '.' is assumed, which means "start from current directory."
# Command:
# find . -name file.txt
# Output: (displays where file.txt is. If it doesn't exist, there is no output. For me, it showed:)
# ./file.txt


# Q21. Description: sort writes sorted concatenation of all FILE(s) to standard output. In other words, it prints the contents of the file by sorting each line.
# Command:
# sort file.txt
#
# file.txt consists of the following lines:
# 5. Fifth line
# 4. Fourth line
# 3. Third line
# 2. Second line
# 1. First line
#
# Output:
# 1. First line
# 2. Second line
# 3. Third line
# 4. Fourth line
# 5. Fifth line


# Q22. Description: ps displays information about a selection of the active processes.
# Command:
# ps
# Output:
#  PID  TTY          TIME CMD
#  291  pts/0    00:00:00 bash
#  1248 pts/0    00:00:00 ps


# Q23. Description: chmod changes file mode bits. A numeric mode is from one to four octal digits (0-7), derived by adding up the bits with values 4, 2, and 1. Omitted digits are assumed to be leading zeros. 777 grants read (4), write (2), and execute (1) permissions to everyone: the owner (1st 7), the group (2nd 7), and others (3rd 7).
# Command:
# chmod 777 hello.txt
# Output:
# None (if file exists)
# chmod: cannot access 'hello.txt': No such file or directory (if file doesn't exist)


# Q24. Description: grep searches for PATTERNS in each FILE. It prints each line that matches a pattern.
# hello.txt has following lines —
# 1. hello World! 
# 2. Hello Universe!
# 3. Hello Multiverse!
# 4. Hellooo verse!
# Command:
# grep "Hello" hello.txt
# Output:
# 2. Hello Universe!
# 3. Hello Multiverse!


# Q25. Description: touch is used to create an empty file or update the timestamp of an existing file.
# Command:
# touch new.txt
# Output:
# (None) 
# Can be checked by stat hello.txt, before and after the command. 
# stat hello.txt
# Before:
# Change: 2025-07-25 13:20:58.806533325 +0530
# Birth: 2025-07-25 13:20:58.804533332 +0530
# After:
# Change: 2025-07-25 13:22:57.274112248 +0530
# Birth: 2025-07-25 13:20:58.804533332 +0530


# Q26. Description: more is a primitive pager to view text one screenful at a time. less is similar but has more features and supports both forward and backward scrolling.
# Command:
# more new.txt
# less new.txt
# Output:
# Shows new.txt. Use Space to scroll.
# more: cannot open new.txt: No such file or directory (if file does not exit)


# Q27. Description: head displays the first 10 lines of a file. tail displays the last 10 lines.
# Command:
# head A2_02_1A.sh
# tail A2
# Output:
# #!/bin/bash … 1st line to
# # 10 th line
# First 10 lines of A2_02_1A.sh
# Error:
# tail: cannot open 'A2' for reading: No such file or directory(if file doesnot exit)


# Q28. Description: top provides a dynamic real-time view of a running system. It shows system summary information and a list of processes.
# Command:
# top
# Output:
# Tasks: 226 total,   1 running, 225 sleeping,   0 stopped,   0 zombie
# %Cpu(s):  0.2 us,  0.2 sy,  0.0 ni, 99.3 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
# MiB Mem :   3914.8 total,    575.9 free,   2185.6 used,   1153.3 buff/cache
# MiB Swap:   3896.0 total,   3865.8 free,     30.2 used.   1698.9 avail Mem
# ...


# Q29. Description: kill sends a signal to a process, usually to stop it.
# Before: a file is opened by gedit try.txt
# From top command, we get PID=8680
# 8680 aroy      20   0  636732  64996  43108 S   4.7   1.6   0:00.85 gedit 
# Command:
# kill 8680
# Output:
# None
# The process (ie here, gedit) is terminated. Text Editor tab closes. Not saved.


# Q30. Description: history shows a list of previously executed commands.
# Command:
# history
# Output:
# ...
#   608  man kill
#   609  top
#   610  man top
#   611  top
#   612  cls
#   613  top
#   614  kill 8680
#   615  top


# Q31. Description: du summarizes disk usage of files and directories. File sizes are rounded to the nearest disk block (typically 4 KB).
# Command:
# du A2_02_1A.sh
# Output:
# 12    A2_02_1A.sh
# 12 means 12 units of block size(1 KB). Files are stored in 4 KB whole blocks, even if 1 is partially used. So 8.3 kB takes 12kB space.


# Q32. Description: ping sends ICMP ECHO_REQUEST packets to network hosts and reports their responses.
# Command:
# ping google.com
# Output:
# PING google.com (142.250.183.174) 56(84) bytes of data.
# 64 bytes from lcmaaa-ar-in-f14.1e100.net (142.250.183.174): icmp_seq=1 ttl=116 time=57.5 ms
# ^C
# --- google.com ping statistics ---
# 1 packets transmitted, 1 received, 0% packet loss, time 0ms
# rtt min/avg/max/mdev = 57.528/57.528/57.528/0.000 ms
#
# if no ip is provided, ie ping, then it gives an error:
# ping: usage error: Destination address required


# Q33. Description: wc counts newline, word, and byte counts for each file.
# Command:
# wc hello.txt
# Output:
#  4 12 75 hello.txt I
# If the file doesn't exist, it outputs an error:
# wc: hello.txt: No such file or directory


# Q34. Description: > redirects standard output to a file (overwrites existing content). >> appends to a file. If the file doesn't exist, it creates one.
# Command:
# echo hello > hello.txt
# Output:
# hello.txt contains "hello"
# Command:
# echo hello >> hello.txt
# Output:
# hello.txt now contains:
# hello
# hello


# Q35. Description: | (pipe) passes the standard output of one command as standard input to another.
# Command:
# ls | grep ".txt"
# Output:
# hello.txt
# new.txt










